name             'odi-base'
maintainer       'The Open Data Institute'
maintainer_email 'tech@theodi.org'
license          'MIT'
description      'Installs/Configures chef-odi-base'
long_description 'Installs/Configures chef-odi-base'
version          '0.1.3'

depends 'odi-apt'
depends 'chef-client'
depends 'git'
depends 'odi-monitoring'
depends 'envbuilder'
depends 'odi-pk'
